name: LCNN_LFCC
n_gpu: 1

arch:
  type: LightCNN
  args:
    first_dim: 180
    second_dim: 600

loss:
  type: CrossEntropyLoss
  args: []

data:
  train:
    batch_size: 64
    num_workers: 4
    datasets:
      - type: LADataset
        args:
          max_len: 600
          wav_dir: data/LA/ASVspoof2019_LA_train/flac
          txt_path: data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
          use_buffer: False
          type: "LFCC"

  test:
    batch_size: 64
    num_workers: 4
    datasets:
      - type: LADataset
        args:
          max_len: 600
          wav_dir: data/LA/ASVspoof2019_LA_eval/flac
          txt_path: data/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
          type: "LFCC"


optimizer:
  type: Adam
  args:
    lr: 3e-4

lr_scheduler:
  type: ExponentialLR
  args:
    gamma: 0.85

metrics:
  - loss
  - grad_norm
  - accuracy
  - roc_auc
  - eer

trainer:
  epochs: 10
  save_dir: saved/
  save_period: 2
  verbosity: 2
  visualize: wandb
  wandb_project: as_project
  grad_norm_clip: null
  grad_max_abs: null
  mixed_precision: false
  eval_interval: 1

resume: null

device: cuda

hydra:
  run:
    dir: .

test_settings:
  sample_rate: 16000
  skip_test: true
  audio_dir: "test_data"